CREATE TABLE "POI" (
	"ID" bigint AUTO_INCREMENT PRIMARY KEY  ,
	"DESCPOI" TEXT NOT NULL,
	"COORDENADAX" INTEGER NOT NULL,
	"COORDENADAY" INTEGER NOT NULL
);

INSERT INTO "POI" ("DESCPOI", "COORDENADAX", "COORDENADAY") VALUES ( 'Lanchonete',27,12);
INSERT INTO "POI" ("DESCPOI", "COORDENADAX", "COORDENADAY") VALUES ( 'Joalheria',15,12);
INSERT INTO "POI" ("DESCPOI", "COORDENADAX", "COORDENADAY") VALUES ( 'Floricultura',19,21);
INSERT INTO "POI" ("DESCPOI", "COORDENADAX", "COORDENADAY") VALUES ( 'Posto',31,18);
INSERT INTO "POI" ("DESCPOI", "COORDENADAX", "COORDENADAY") VALUES ( 'Pub',12,8);
INSERT INTO "POI" ("DESCPOI", "COORDENADAX", "COORDENADAY") VALUES ( 'SuperMercado',23,6);
INSERT INTO "POI" ("DESCPOI", "COORDENADAX", "COORDENADAY") VALUES ( 'Churrascaria',28,2);